# 1.Импрот библиотеки Numpy

In [34]:
import numpy as np

# 2.Примеры создания массивов

In [35]:
# Одномерный массив
list = [1, 2, 3, 4, 5]
array = np.array(list)

print(list, type(list))
print(array, type(array))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [36]:
# Двумерный массив
twice_d_list = [[1, 2, 3], [4, 5, 6]]
twice_d_array = np.array(twice_d_list)

print(twice_d_list, type(twice_d_list), end="\n\n")
print(twice_d_array, type(twice_d_array))

[[1, 2, 3], [4, 5, 6]] <class 'list'>

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [37]:
# N-мерный массив
n_d_array = np.full((4,2,5,2,5), 8)

print(n_d_array)

[[[[[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]]


  [[[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]]]



 [[[[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]]


  [[[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]]]



 [[[[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]]


  [[[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]

   [[8 8 8 8 8]
    [8 8 8 8 8]]



In [38]:
# Заполнено нулями
zeros = np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
# Заполнено единицами
ones = np.ones((4,4,4))
print(ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [40]:
# Заполнено в промежутке
arange = np.arange(0,108)
print(arange)


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107]


In [41]:
# Заполнено рандомными float
rnd_array = np.random.random(9)
rnd_array_res = rnd_array.reshape(3,3)

print(rnd_array, end="\n\n") # просто 9 элементов
print(rnd_array_res) # перестроены в форму 3х3

[0.29465436 0.79810987 0.76543959 0.9818609  0.80024755 0.87859582
 0.38113515 0.667959   0.83317096]

[[0.29465436 0.79810987 0.76543959]
 [0.9818609  0.80024755 0.87859582]
 [0.38113515 0.667959   0.83317096]]


# 3.Демонстрация атрибутов

In [42]:
# Размер массива и тип данных в нём
two_d_array = np.array([[1, 2.6, 3], [4, 5, 6.0]])
nx_d_array = np.full((2,4,1,5), 7)
str_array = np.array((["tomato", "red bean buns", "melon"], ["Zhu Yuan", "Yanagi", "Miyabi"]))

print(two_d_array.shape, two_d_array.dtype)
print(nx_d_array.shape, nx_d_array.dtype)
print(str_array.shape, str_array.dtype) # строка юникод и максимальная длина 13 символов

(2, 3) float64
(2, 4, 1, 5) int64
(2, 3) <U13


# 4.Примеры индексирования и срезов

In [43]:
# Получение определённого элемента и подмассива
sl_array = np.arange(58, 90)

print(sl_array[4])
print(sl_array[3:9])

62
[61 62 63 64 65 66]


# 5.Примеры векторных операций и базовых статистик

In [44]:
first_array = np.array([[1,2,3], [89, 20, 1]])
second_array = np.array([[9, 4.3, 1], [1, 2, 10]])


In [ ]:
# Поэлементное сложение массивов
summed_array = first_array + second_array
print(summed_array, end="\n\n")

# Поэлементно вычитание массивов
substracted_array = first_array - second_array
print(substracted_array, end="\n\n")

# Поэлементно перемножение массивов
multiplied_array = first_array * second_array
print(multiplied_array, end="\n\n")

# Поэлементно деление массивов
div_array = first_array / second_array
print(div_array)

[[10.   6.3  4. ]
 [90.  22.  11. ]]

[[-8.  -2.3  2. ]
 [88.  18.  -9. ]]

[[ 9.   8.6  3. ]
 [89.  40.  10. ]]

[[ 0.11111111  0.46511628  3.        ]
 [89.         10.          0.1       ]]


In [60]:
# Среднее значение
print(np.mean(first_array))
print(np.mean(second_array), end="\n\n")

# Медиана
print(np.median(first_array))
print(np.median(second_array), end="\n\n")

# Стандартное отклонение
print(np.std(first_array))
print(np.std(second_array), end="\n\n")

# Дисперсия
print(np.var(first_array))
print(np.var(second_array), end="\n\n")

19.333333333333332
4.55

2.5
3.15

31.867782407245656
3.6804664559445905

1015.5555555555557
13.545833333333334

